In [4]:
import pandas as pd

In [6]:
df = pd.read_csv("spotifyprueba.csv")

In [8]:
df.head()

,Unnamed: 0,track_name,artist_name,track_id,popularity,duration_ms,artist_genres
0,0,Die With A Smile,Lady Gaga,2plbrEY59IikOBgBGLjaoe,100,251667,"art pop, dance pop, pop"
1,1,BIRDS OF A FEATHER,Billie Eilish,6dOtVTDdiauQNBQEDOtlAB,98,210373,"art pop, pop"
2,2,Who,Jimin,7tI8dRuH2Yc6RuoTjxo4dU,93,170887,k-pop
3,3,Taste,Sabrina Carpenter,5G2f63n7IPVPPjfNIGih7Q,95,157279,pop
4,4,Espresso,Sabrina Carpenter,2HRqTpkrJO5ggZyyK6NPWz,87,175459,pop

In [10]:
df.loc[df['artist_genres'].str.contains("canadian contemporary r&b|canadian pop|pop", case=False, na=False), 'artist_genres'] = 'pop'
df.loc[df['artist_genres'].str.contains("hip hop|rap|slap|alternative", case=False, na=False), 'artist_genres'] = "hip hop"
df.loc[df['artist_genres'].str.contains("rock", case=False, na=False), 'artist_genres'] = "rock"
df.loc[df['artist_genres'].str.contains("reggaeton|urbano latino|boricua|corrido|chill", case=False, na=False), 'artist_genres'] = "urbano latino"
df.loc[df['artist_genres'].str.contains("alt z|indie|melodic|krushclub", case=False, na=False), 'artist_genres'] = "indie"

In [12]:
df["artist_genres"].value_counts()

artist_genres
pop              59
hip hop          17
urbano latino    11
indie             6
rock              3
Name: count, dtype: int64

In [14]:
df.dropna(how="all")

,Unnamed: 0,track_name,artist_name,track_id,popularity,duration_ms,artist_genres
0,0,Die With A Smile,Lady Gaga,2plbrEY59IikOBgBGLjaoe,100,251667,pop
1,1,BIRDS OF A FEATHER,Billie Eilish,6dOtVTDdiauQNBQEDOtlAB,98,210373,pop
2,2,Who,Jimin,7tI8dRuH2Yc6RuoTjxo4dU,93,170887,pop
3,3,Taste,Sabrina Carpenter,5G2f63n7IPVPPjfNIGih7Q,95,157279,pop
4,4,Espresso,Sabrina Carpenter,2HRqTpkrJO5ggZyyK6NPWz,87,175459,pop
...,...,...,...,...,...,...,...
95,95,As It Was,Harry Styles,4Dvkj6JhhA12EX05fT7y2e,87,167303,pop
96,96,Big Dawgs,Hanumankind,0OA00aPt3BV10qeMIs3meW,89,190666,hip hop
97,97,Shut up My Moms Calling,Hotel Ugly,3hxIUxnT27p5WcmjGUXNwx,86,164571,pop
98,98,Nonsense,Sabrina Carpenter,6dgUya35uo964z7GZXM07g,87,163648,pop
99,99,Good Graces,Sabrina Carpenter,102YUQbYmwdBXS7jwamI90,88,185265,pop

In [16]:
df_features = pd.read_csv("spotifyfeatures.csv")

In [18]:
df_features.head()

,Unnamed: 0,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,type,id,uri,track_href,analysis_url,duration_ms,time_signature
0,0,0.521,0.592,6,-7.777,0,0.0304,0.30800,0.000000,0.122,0.535,157.969,audio_features,2plbrEY59IikOBgBGLjaoe,spotify:track:2plbrEY59IikOBgBGLjaoe,https://api.spotify.com/v1/tracks/2plbrEY59Iik...,https://api.spotify.com/v1/audio-analysis/2plb...,251668,3
1,1,0.747,0.507,2,-10.171,1,0.0358,0.20000,0.060800,0.117,0.438,104.978,audio_features,6dOtVTDdiauQNBQEDOtlAB,spotify:track:6dOtVTDdiauQNBQEDOtlAB,https://api.spotify.com/v1/tracks/6dOtVTDdiauQ...,https://api.spotify.com/v1/audio-analysis/6dOt...,210373,4
2,2,0.660,0.756,0,-3.743,0,0.0320,0.00289,0.000000,0.193,0.838,116.034,audio_features,7tI8dRuH2Yc6RuoTjxo4dU,spotify:track:7tI8dRuH2Yc6RuoTjxo4dU,https://api.spotify.com/v1/tracks/7tI8dRuH2Yc6...,https://api.spotify.com/v1/audio-analysis/7tI8...,170888,4
3,3,0.674,0.907,3,-4.086,1,0.0640,0.10100,0.000000,0.297,0.721,112.964,audio_features,5G2f63n7IPVPPjfNIGih7Q,spotify:track:5G2f63n7IPVPPjfNIGih7Q,https://api.spotify.com/v1/tracks/5G2f63n7IPVP...,https://api.spotify.com/v1/audio-analysis/5G2f...,157280,4
4,4,0.699,0.776,0,-5.282,1,0.0293,0.13100,0.000005,0.205,0.708,103.963,audio_features,2HRqTpkrJO5ggZyyK6NPWz,spotify:track:2HRqTpkrJO5ggZyyK6NPWz,https://api.spotify.com/v1/tracks/2HRqTpkrJO5g...,https://api.spotify.com/v1/audio-analysis/2HRq...,175459,4

In [20]:
df_features.rename(columns={"id": "track_id"}, inplace=True)

In [22]:
df_combined = pd.merge(df, df_features, left_on='track_id', right_on='track_id', how='inner')

In [24]:
df_combined.columns

Index(['Unnamed: 0_x', 'track_name', 'artist_name', 'track_id', 'popularity',
       'duration_ms_x', 'artist_genres', 'Unnamed: 0_y', 'danceability',
       'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'type', 'uri',
       'track_href', 'analysis_url', 'duration_ms_y', 'time_signature'],
      dtype='object')

In [136]:
df_features1= df_combined[["artist_name","popularity","artist_genres","danceability","energy","speechiness","instrumentalness","valence"]]

In [138]:
df_features1.head()

,artist_name,popularity,artist_genres,danceability,energy,speechiness,instrumentalness,valence
0,Lady Gaga,100,pop,0.521,0.592,0.0304,0.000000,0.535
1,Billie Eilish,98,pop,0.747,0.507,0.0358,0.060800,0.438
2,Jimin,93,pop,0.660,0.756,0.0320,0.000000,0.838
3,Sabrina Carpenter,95,pop,0.674,0.907,0.0640,0.000000,0.721
4,Sabrina Carpenter,87,pop,0.699,0.776,0.0293,0.000005,0.708

In [140]:
df_features_1 = df_features_1.groupby("artist_genres")[["danceability", "energy", "speechiness", "instrumentalness", "valence"]].agg("mean").reset_index()

In [156]:
df_final_1 = pd.concat([df_features1, df_features_1], axis=0)  # Para concatenar filas

In [186]:
df_final_1.head()

,artist_name,popularity,artist_genres,danceability,energy,speechiness,instrumentalness,valence
0,Lady Gaga,100.0,pop,0.521,0.592,0.0304,0.000000,0.535
1,Billie Eilish,98.0,pop,0.747,0.507,0.0358,0.060800,0.438
2,Jimin,93.0,pop,0.660,0.756,0.0320,0.000000,0.838
3,Sabrina Carpenter,95.0,pop,0.674,0.907,0.0640,0.000000,0.721
4,Sabrina Carpenter,87.0,pop,0.699,0.776,0.0293,0.000005,0.708

In [294]:
df_final_1["speechiness"].mode().mean()

0.0436

In [30]:
df2 = pd.read_csv("spotify2dfsinfeatures.csv")

In [32]:
df2features = pd.read_csv("spotifyfeatures2.csv")

In [34]:
df2features.rename(columns={"id": "track_id"}, inplace=True)

In [36]:
df_combined2 = pd.merge(df2, df2features, left_on='track_id', right_on='track_id', how='inner')

In [106]:
df_features2= df_combined2[["artist_name","popularity","artist_genres","danceability","energy","speechiness","instrumentalness","valence"]]

In [108]:
df_features2.head()

,artist_name,popularity,artist_genres,danceability,energy,speechiness,instrumentalness,valence
0,John Lennon,76,"classic rock, rock",0.547,0.257,0.0252,0.183000,0.169
1,Queen,71,"classic rock, glam rock, rock",0.390,0.395,0.0501,0.000000,0.247
2,The Beatles,58,"british invasion, classic rock, merseybeat, ps...",0.399,0.555,0.0259,0.000013,0.663
3,Michael Jackson,77,"r&b, soul",0.920,0.654,0.0401,0.015300,0.847
4,The Rolling Stones,76,"album rock, british invasion, classic rock, rock",0.723,0.863,0.0338,0.031700,0.931

In [174]:
df_features2.loc[df_features2['artist_genres'].str.contains("metal|rock", case=False, na=False), 'artist_genres'] = 'rock'
df_features2.loc[df_features2['artist_genres'].str.contains("hip hop|rap|slap|alternative", case=False, na=False), 'artist_genres'] = "hip hop"
df_features2.loc[df_features2['artist_genres'].str.contains("pop", case=False, na=False), 'artist_genres'] = "pop"
df_features2.loc[df_features2['artist_genres'].str.contains("standards|jazz|funk|soul|advocacy|reggae", case=False, na=False), 'artist_genres'] = "jazz, blues, r&b"

In [176]:
df_features2["artist_genres"].value_counts()

artist_genres
rock                76
jazz, blues, r&b    12
pop                 10
hip hop              2
Name: count, dtype: int64

In [178]:
df_features_2= df_features_2.groupby("artist_genres")[["danceability", "energy", "speechiness", "instrumentalness", "valence"]].agg("mean").reset_index()

In [24]:
#df_features_1 = We have a playlist with the features of the most listened playlist of User 1
#df_features_2 = We have a playlist with the features of the most listened playlist of User 2

In [182]:
df_final_2 = pd.concat([df_features2, df_features_2], axis=0)  # Para concatenar filas

In [184]:
df_final_2.head()

,artist_name,popularity,artist_genres,danceability,energy,speechiness,instrumentalness,valence
0,John Lennon,76.0,rock,0.547,0.257,0.0252,0.183000,0.169
1,Queen,71.0,rock,0.390,0.395,0.0501,0.000000,0.247
2,The Beatles,58.0,rock,0.399,0.555,0.0259,0.000013,0.663
3,Michael Jackson,77.0,"jazz, blues, r&b",0.920,0.654,0.0401,0.015300,0.847
4,The Rolling Stones,76.0,rock,0.723,0.863,0.0338,0.031700,0.931

In [290]:
df_final_2["speechiness"].mode().mean()

0.0298

In [190]:
df_final_2.to_csv("df_final_2")

In [188]:
df_final_1.head()

,artist_name,popularity,artist_genres,danceability,energy,speechiness,instrumentalness,valence
0,Lady Gaga,100.0,pop,0.521,0.592,0.0304,0.000000,0.535
1,Billie Eilish,98.0,pop,0.747,0.507,0.0358,0.060800,0.438
2,Jimin,93.0,pop,0.660,0.756,0.0320,0.000000,0.838
3,Sabrina Carpenter,95.0,pop,0.674,0.907,0.0640,0.000000,0.721
4,Sabrina Carpenter,87.0,pop,0.699,0.776,0.0293,0.000005,0.708

In [192]:
df_final_1.to_csv("df_final_1")

In [206]:
df_features_1.head()

,artist_genres,danceability,energy,speechiness,instrumentalness,valence
0,hip hop,0.632647,0.724941,0.090600,0.001310,0.456706
1,indie,0.543333,0.557000,0.042317,0.125360,0.364133
2,pop,0.622017,0.631508,0.053727,0.035998,0.545271
3,rock,0.603333,0.578333,0.039067,0.008339,0.489000
4,urbano latino,0.776545,0.603636,0.072600,0.000110,0.720636

In [204]:
df_features_2.head()

,artist_genres,danceability,energy,speechiness,instrumentalness,valence
0,hip hop,0.668000,0.624500,0.163150,0.000360,0.222500
1,"jazz, blues, r&b",0.658167,0.565083,0.053842,0.001404,0.679417
2,pop,0.599200,0.688900,0.037410,0.000610,0.536320
3,rock,0.517395,0.638092,0.054046,0.041877,0.545289

In [250]:
danceability1 =df_features_1["danceability"].mean()
energy1 = df_features_1["energy"].mean()
instrumentalness1 =df_features_1["instrumentalness"].mean()
valence1 =df_features_1["valence"].mean()


print(danceability1,
      energy1,
      instrumentalness1,
      valence1)

0.6355752258376387 0.6190838696033113 0.034223480767576066 0.5151493531526633

In [214]:
danceability2 =df_features_2["danceability"].mean()
energy2 = df_features_2["energy"].mean()
speechiness2 =df_features_2["speechiness"].mean()
instrumentalness2 =df_features_2["instrumentalness"].mean()
valence2 =df_features_2["valence"].mean()

print(danceability2,
      energy2,
      speechiness2,
      instrumentalness2,
      valence2)

0.6106903508771929 0.6291438596491228 0.07711192982456141 0.011062769070175438 0.49588153508771926

In [292]:
#We need to find porcentual difference between both playlist, finiding first the average of each feature of each user's playlist

danceability_d = ((danceability1 - danceability2) / danceability2) * 100
energy_d = ((energy1 - energy2) / energy2) * 100
valence_d= ((valence1 - valence2) / valence2) * 100

print("Difference % :")
print(f"Danceability: {danceability_d:.2f}%")
print(f"Energy: {energy_d:.2f}%")
print(f"Valence: {valence_d:.2f}%")

Difference % :
Danceability: 4.07%
Energy: -1.60%
Valence: 3.89%